import Vue from 'vue'
import 'element-ui/lib/theme-chalk/index.css';
import { Button, Menu, MenuItem, Submenu, Avatar, Dropdown, DropdownMenu, DropdownItem, Rate, InputNumber
        , Collapse, CollapseItem, Tag, Input, Radio, RadioGroup,Form, FormItem, Pagination, Select, Option, Loading} from 'element-ui';
Vue.use(Button)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Rate)
Vue.use(InputNumber)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Tag)
Vue.use(Input)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Pagination)
Vue.use(Select)
Vue.use(Option)
Vue.use(Loading)